apiVersion: v1
kind: Pod
metadata:
  name: gke-training-pod
spec:
  restartPolicy: Never
  containers:
  - name: tf-demo-mnist
    image: gcr.io/ndixita-demo/tf:20240314_183239
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 1
